import { reactive } from 'vue'

let apiHost = ''
let liveHost = ''
if (process.env.NODE_ENV === 'development') {
	apiHost = 'http://localhost:3001'
	liveHost = 'http://localhost:3004'
}
if (process.env.NODE_ENV === 'production') {
	apiHost = 'https://web.mooc.chaikd.com'
	liveHost = 'https://console.mooc.chaikd.com'
}

const state = reactive({
	apiHost,
	liveHost
})

export function useHost() {
  return state
}